name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - name: Install dependencies
      working-directory: ChatterinoUpdater
      run: dotnet restore

    - name: Build
      working-directory: ChatterinoUpdater
      run: |
        dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true
        dotnet publish -c Release -r win-arm64 --self-contained -p:PublishSingleFile=true

    - name: tree
      run: |
        tree /F

    - name: Package
      shell: pwsh
      run: |
        mkdir pkg
        mkdir pkg/x64
        mkdir pkg/arm64
        cp ./ChatterinoUpdater/ChatterinoUpdater/bin/Release/net10.0/win-x64/publish/ChatterinoUpdater.exe ./pkg/x64
        cp ./ChatterinoUpdater/ChatterinoUpdater/bin/Release/net10.0/win-arm64/publish/ChatterinoUpdater.exe ./pkg/arm64

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: ChatterinoPortableUpdater
        path: pkg/*
